FROM python:2
RUN python -m pip install robotframework
RUN python -m pip install --upgrade robotframework-httplibrary
RUN python -m pip install requests
RUN python -m pip install robotframework-requests
COPY . /robot
